Release 8.7.0

diff --git a/.github/workflows/maven-publish.yml b/.github/workflows/maven-publish.yml
--- a/.github/workflows/maven-publish.yml
+++ b/.github/workflows/maven-publish.yml
@@ -1,38 +1,69 @@
 # This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
 # For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path
 
-name: Maven Package
+name: Release to Maven Central
 on:
   release:
     types: [published]
 
+permissions:
+  contents: read
+  packages: write
+
 jobs:
   build:
     runs-on: ubuntu-latest
-    permissions:
-      contents: read
-      packages: write
 
     steps:
-    - uses: actions/checkout@v3
+    - uses: actions/checkout@v4
+
     - uses: actions/setup-java@v3
       with:
         distribution: 'temurin' # See 'Supported distributions' for available options
         java-version: '8'
-        server-id: 'ossrh'
+        server-id: 'central'
         server-username: OSSRH_USERNAME
         server-password: OSSRH_PASSWORD
         gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
         gpg-passphrase : SIGN_KEY_PASS
+
+    # Install Maven 3.9.9 if it's not already installed
+    - name: Install Maven (specific version 3.9.9)
+      run: |
+        # Check if Maven is already installed
+        if ! mvn -version &>/dev/null; then
+          echo "Maven not found. Installing Maven 3.9.9..."
         
+          # Update package list and install required dependencies
+          sudo apt-get update
+          sudo apt-get install -y wget
+
+          # Download Maven 3.9.9 tar.gz
+          wget https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz
+
+          # Extract and move Maven to /opt
+          sudo tar -xvzf apache-maven-3.9.9-bin.tar.gz -C /opt
+
+          # Set up environment variables for Maven
+          sudo ln -s /opt/apache-maven-3.9.9 /opt/maven
+          sudo ln -s /opt/maven/bin/mvn /usr/bin/mvn
+
+          # Clean up the downloaded tar.gz file
+          rm apache-maven-3.9.9-bin.tar.gz
+
+          echo "Maven 3.9.9 installed successfully!"
+        else
+          echo "Maven is already installed."
+        fi
+
     - name: Build with Maven
       id: build
       run: mvn -B package --file pom.xml
     
-    - name: Publish with Maven
+    - name: Publish to Maven Central
       id: deploy
-      run: mvn -U -B clean deploy -P release -DskipTests=true
       env:
         SIGN_KEY_PASS: ${{ secrets.SIGN_KEY_PASS }}
         OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
         OSSRH_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
+      run: mvn -U -B clean deploy -P release -DskipTests=true
